baseURL = "/"
languageCode = "en-us"
[[menu.main]]
Name = "About"
url = "/about"
[params]
SiteLogo = "/IJM_Logo_Horizontal_White_ForWeb.png"
footerContent = "Copyright 2003-2021 | IJM Philippines "
menuButtonText = "Would you like to learn more? "
